### ISSUE TITLE
Ability to choose where the folder is downloaded

### ISSUE THREAD

**Issue by samcool2010** [nobodyme/reddit-fetch#4]
Hi I love your project and just stumbled upon it the other day. I had trouble getting to work with windows task scheduler but I finally did with a bat file. Issue I am having is that since I am using Task Schedule it drops the folder in C:\Windows\System32 directory. Which is a pain. Would it be possible to change the location of the downloaded pictures?

**Comment by nobodyme** [comment]
Hi, glad that you loved the project, I understand your pain and I now added support for optionally specifying the directory location with a new -loc parameter. It works on mac and linux and it should work in windows too but I don't have a windows machine to test. So let me know if it goes well with you as well. Have a great day :)
